version: "3.9"

services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - 8081:8080
    restart: always
    volumes:
      - ./swagger:/swagger
    environment:
      SWAGGER_JSON: /swagger/sample_service.swagger.json
    networks:
      - grpc2

networks:
  grpc2:
    driver: bridge
