// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: my/my.proto

package protos_1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ParamValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to ValueOneof:
	//	*ParamValue_Double
	//	*ParamValue_Int
	//	*ParamValue_Bool
	//	*ParamValue_String_
	ValueOneof isParamValue_ValueOneof `protobuf_oneof:"value_oneof"`
}

func (x *ParamValue) Reset() {
	*x = ParamValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_my_my_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParamValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamValue) ProtoMessage() {}

func (x *ParamValue) ProtoReflect() protoreflect.Message {
	mi := &file_my_my_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamValue.ProtoReflect.Descriptor instead.
func (*ParamValue) Descriptor() ([]byte, []int) {
	return file_my_my_proto_rawDescGZIP(), []int{0}
}

func (m *ParamValue) GetValueOneof() isParamValue_ValueOneof {
	if m != nil {
		return m.ValueOneof
	}
	return nil
}

func (x *ParamValue) GetDouble() float64 {
	if x, ok := x.GetValueOneof().(*ParamValue_Double); ok {
		return x.Double
	}
	return 0
}

func (x *ParamValue) GetInt() int64 {
	if x, ok := x.GetValueOneof().(*ParamValue_Int); ok {
		return x.Int
	}
	return 0
}

func (x *ParamValue) GetBool() bool {
	if x, ok := x.GetValueOneof().(*ParamValue_Bool); ok {
		return x.Bool
	}
	return false
}

func (x *ParamValue) GetString_() string {
	if x, ok := x.GetValueOneof().(*ParamValue_String_); ok {
		return x.String_
	}
	return ""
}

type isParamValue_ValueOneof interface {
	isParamValue_ValueOneof()
}

type ParamValue_Double struct {
	Double float64 `protobuf:"fixed64,1,opt,name=double,proto3,oneof"`
}

type ParamValue_Int struct {
	Int int64 `protobuf:"varint,2,opt,name=int,proto3,oneof"`
}

type ParamValue_Bool struct {
	Bool bool `protobuf:"varint,3,opt,name=bool,proto3,oneof"`
}

type ParamValue_String_ struct {
	String_ string `protobuf:"bytes,4,opt,name=string,proto3,oneof"`
}

func (*ParamValue_Double) isParamValue_ValueOneof() {}

func (*ParamValue_Int) isParamValue_ValueOneof() {}

func (*ParamValue_Bool) isParamValue_ValueOneof() {}

func (*ParamValue_String_) isParamValue_ValueOneof() {}

type SellerParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result []*SellerParams_Item `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
}

func (x *SellerParams) Reset() {
	*x = SellerParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_my_my_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SellerParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellerParams) ProtoMessage() {}

func (x *SellerParams) ProtoReflect() protoreflect.Message {
	mi := &file_my_my_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellerParams.ProtoReflect.Descriptor instead.
func (*SellerParams) Descriptor() ([]byte, []int) {
	return file_my_my_proto_rawDescGZIP(), []int{1}
}

func (x *SellerParams) GetResult() []*SellerParams_Item {
	if x != nil {
		return x.Result
	}
	return nil
}

type SellerParams_Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SellerId int64                  `protobuf:"varint,1,opt,name=seller_id,json=sellerId,proto3" json:"seller_id,omitempty"`
	Rating   float64                `protobuf:"fixed64,2,opt,name=rating,proto3" json:"rating,omitempty"`
	Params   map[string]*ParamValue `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *SellerParams_Item) Reset() {
	*x = SellerParams_Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_my_my_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SellerParams_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellerParams_Item) ProtoMessage() {}

func (x *SellerParams_Item) ProtoReflect() protoreflect.Message {
	mi := &file_my_my_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellerParams_Item.ProtoReflect.Descriptor instead.
func (*SellerParams_Item) Descriptor() ([]byte, []int) {
	return file_my_my_proto_rawDescGZIP(), []int{1, 0}
}

func (x *SellerParams_Item) GetSellerId() int64 {
	if x != nil {
		return x.SellerId
	}
	return 0
}

func (x *SellerParams_Item) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *SellerParams_Item) GetParams() map[string]*ParamValue {
	if x != nil {
		return x.Params
	}
	return nil
}

var File_my_my_proto protoreflect.FileDescriptor

var file_my_my_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x6d, 0x79, 0x2f, 0x6d, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x67,
	0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2e, 0x73, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x2e, 0x64, 0x65, 0x6d,
	0x6f, 0x22, 0x79, 0x0a, 0x0a, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x18, 0x0a, 0x06, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x48,
	0x00, 0x52, 0x06, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x03, 0x69, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x03, 0x69, 0x6e, 0x74, 0x12, 0x14, 0x0a,
	0x04, 0x62, 0x6f, 0x6f, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x04, 0x62,
	0x6f, 0x6f, 0x6c, 0x12, 0x18, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x42, 0x0d, 0x0a,
	0x0b, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x5f, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x22, 0xb1, 0x02, 0x0a,
	0x0c, 0x53, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x3d, 0x0a,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e,
	0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2e, 0x73, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x2e, 0x64, 0x65,
	0x6d, 0x6f, 0x2e, 0x53, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x2e,
	0x49, 0x74, 0x65, 0x6d, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x1a, 0xe1, 0x01, 0x0a,
	0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x65, 0x6c, 0x6c, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x49, 0x0a, 0x06, 0x70, 0x61,
	0x72, 0x61, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x67, 0x6f, 0x6c,
	0x61, 0x6e, 0x67, 0x2e, 0x73, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e,
	0x53, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x2e, 0x49, 0x74, 0x65,
	0x6d, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x70,
	0x61, 0x72, 0x61, 0x6d, 0x73, 0x1a, 0x59, 0x0a, 0x0b, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x34, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2e, 0x73,
	0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61,
	0x6c, 0x65, 0x78, 0x65, 0x79, 0x6b, 0x69, 0x72, 0x69, 0x6e, 0x79, 0x75, 0x6b, 0x2f, 0x6c, 0x65,
	0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x2d, 0x67, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2d, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_my_my_proto_rawDescOnce sync.Once
	file_my_my_proto_rawDescData = file_my_my_proto_rawDesc
)

func file_my_my_proto_rawDescGZIP() []byte {
	file_my_my_proto_rawDescOnce.Do(func() {
		file_my_my_proto_rawDescData = protoimpl.X.CompressGZIP(file_my_my_proto_rawDescData)
	})
	return file_my_my_proto_rawDescData
}

var file_my_my_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_my_my_proto_goTypes = []interface{}{
	(*ParamValue)(nil),        // 0: golang.school.demo.ParamValue
	(*SellerParams)(nil),      // 1: golang.school.demo.SellerParams
	(*SellerParams_Item)(nil), // 2: golang.school.demo.SellerParams.Item
	nil,                       // 3: golang.school.demo.SellerParams.Item.ParamsEntry
}
var file_my_my_proto_depIdxs = []int32{
	2, // 0: golang.school.demo.SellerParams.result:type_name -> golang.school.demo.SellerParams.Item
	3, // 1: golang.school.demo.SellerParams.Item.params:type_name -> golang.school.demo.SellerParams.Item.ParamsEntry
	0, // 2: golang.school.demo.SellerParams.Item.ParamsEntry.value:type_name -> golang.school.demo.ParamValue
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_my_my_proto_init() }
func file_my_my_proto_init() {
	if File_my_my_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_my_my_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParamValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_my_my_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SellerParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_my_my_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SellerParams_Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_my_my_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*ParamValue_Double)(nil),
		(*ParamValue_Int)(nil),
		(*ParamValue_Bool)(nil),
		(*ParamValue_String_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_my_my_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_my_my_proto_goTypes,
		DependencyIndexes: file_my_my_proto_depIdxs,
		MessageInfos:      file_my_my_proto_msgTypes,
	}.Build()
	File_my_my_proto = out.File
	file_my_my_proto_rawDesc = nil
	file_my_my_proto_goTypes = nil
	file_my_my_proto_depIdxs = nil
}
